# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1kytWECg62qdtqVyAaplBz4t12AV8_r
"""

import torch
from diffusers import StableDiffusion3Pipeline
from huggingface_hub import login
from google.colab import userdata

from google.colab import userdata
hf_token = userdata.get("HF_TOKEN")
login(token=hf_token)

DEVICE = "cuda"
DTYPE = torch.bfloat16  # SD3.5 recommends bfloat16

pipe = StableDiffusion3Pipeline.from_pretrained(
    "stabilityai/stable-diffusion-3.5-large",
    torch_dtype=DTYPE,
).to(DEVICE)

styles_available = [
    "Cartoon", "Cubism", "Winter", "Pop_Art", "Ukiyoe",
    "Impressionism", "Byzantine", "Van_Gogh", "Bricks", "Watercolor",
]
objects_available = [
    "Architectures", "Bears", "Birds", "Butterfly", "Cats",
    "Dogs", "Fishes", "Flame", "Flowers", "Frogs",
    "Horses", "Human", "Jellyfish", "Rabbits", "Sandwiches",
    "Sea", "Statues", "Towers", "Trees", "Waterfalls",
]

IMAGENET_CLASSES = [
    "tench", "goldfish", "tiger shark", "hammerhead", "electric ray",
    "hen", "ostrich", "brambling", "goldfinch", "house finch",
    "junco", "indigo bunting", "robin", "bulbul", "jay",
    "magpie", "chickadee", "water ouzel", "kite", "bald eagle",
    "vulture", "great grey owl", "mud turtle", "box turtle", "banded gecko",
    "common iguana", "whiptail lizard", "agama", "frilled lizard", "alligator lizard",
    "green mamba", "thunder snake", "ringneck snake", "king snake", "garter snake",
    "vine snake", "trilobite", "scorpion", "black widow", "tarantula",
    "centipede", "grouse", "peacock", "quail", "partridge",
    "macaw", "lorikeet", "coucal", "bee eater", "hornbill"
]

def make_object_prompts(concept, num_prompts=50):
    n = min(num_prompts, len(IMAGENET_CLASSES))
    return [(f"{cls} with {concept}", f"{cls}") for cls in IMAGENET_CLASSES[:n]]

# ── CONFIG ─────────────────────────────────────────────────────────────
CONCEPT         = "Dogs"          # object concept to steer away from
GEN_PROMPT      = f"{CONCEPT} in Cartoon style"

NUM_DIVERSE_PROMPTS = 25
DIVERSE_PAIRS   = make_object_prompts(CONCEPT, NUM_DIVERSE_PROMPTS)

ALPHAS_C   = [100, 250, 500, 1000, 2000]           # CLIP-L sequence — fine around best (10)
ALPHAS_T   = [0, 10, 50, 100, 200, 500]          # T5 — fine around best (20)
ALPHAS_G   = [0, 5]                        # CLIP-G pooled — fixed at best (5)
ALPHAS_CLP = [0, 10, 30]             # CLIP-L pooled — fine around best (5)
NUM_STEPS       = 10
GUIDANCE_SCALE  = 7.0
SEED            = 42
# ────────────────────────────────────────────────────────────────────────
print(f"Diverse prompt pairs: {len(DIVERSE_PAIRS)}")
print(f"  Example pos: '{DIVERSE_PAIRS[0][0]}'")
print(f"  Example neg: '{DIVERSE_PAIRS[0][1]}'")

def masked_mean(act, prompt, tokenizer, max_length):
    tok  = tokenizer(prompt, return_tensors="pt", padding="max_length",
                     max_length=max_length, truncation=True)
    mask = tok.attention_mask[0].bool()
    return act[mask].mean(dim=0)

from tqdm.auto import tqdm

def clear_all_hooks():
    pipe.transformer.time_text_embed._forward_hooks.clear()
    pipe.transformer.time_text_embed._forward_pre_hooks.clear()
    pipe.transformer.context_embedder._forward_hooks.clear()
    pipe.transformer.context_embedder._forward_pre_hooks.clear()
    for blk in pipe.transformer.transformer_blocks:
        blk._forward_hooks.clear()
        blk._forward_pre_hooks.clear()
clear_all_hooks()

# ── Per-step capture via pipeline runs ───────────────────────────────────
# out[1] = conditional embeddings (batch dim 1 under CFG)
# args[1][1] = conditional pooled projections under CFG
def capture(prompt, seed=0):
    ctx_steps, pooled_cache, counter = {}, {}, [0]

    def _ctx_hook(module, inp, out):
        ctx_steps[counter[0]] = out[1].detach().cpu().float()
        counter[0] += 1

    def _pooled_hook(module, args):
        if "pooled" not in pooled_cache:
            pooled_cache["pooled"] = args[1][1].detach().cpu().float()

    h1 = pipe.transformer.context_embedder.register_forward_hook(_ctx_hook)
    h2 = pipe.transformer.time_text_embed.register_forward_pre_hook(_pooled_hook)
    with torch.no_grad():
        pipe(prompt, num_inference_steps=NUM_STEPS, output_type="latent",
             guidance_scale=GUIDANCE_SCALE,
             generator=torch.Generator(DEVICE).manual_seed(seed))
    h1.remove(); h2.remove()
    return ctx_steps, pooled_cache.get("pooled")


# ── Average per-step directions over diverse ImageNet prompt pairs ────────
# Insight from experiments log: single-step direction caused blurring —
# per-step directions are required. Each pair contributes one pos + one neg
# pipeline run; directions are averaged across all pairs then normalised.
#
# Time estimate: 2 × NUM_DIVERSE_PROMPTS pipeline runs.
# Reduce NUM_DIVERSE_PROMPTS (e.g. 20) if this is too slow.

print(f"Computing per-step directions from {len(DIVERSE_PAIRS)} diverse pairs...")
print(f"({2 * len(DIVERSE_PAIRS)} total pipeline runs × {NUM_STEPS} steps each)")

acc_clip        = {step: None for step in range(NUM_STEPS)}
acc_t5          = {step: None for step in range(NUM_STEPS)}
acc_clipl_pooled = None
acc_clipg        = None

for pos_prompt, neg_prompt in tqdm(DIVERSE_PAIRS, desc="Diverse pairs"):
    pos_ctx, pos_pooled = capture(pos_prompt, seed=0)
    neg_ctx, neg_pooled = capture(neg_prompt, seed=0)

    for step in range(NUM_STEPS):
        if step not in pos_ctx or step not in neg_ctx:
            continue
        diff = pos_ctx[step] - neg_ctx[step]   # (seq_len, 3072)

        # CLIP-L direction: masked mean over first 77 tokens
        d_clip = masked_mean(diff[:77], pos_prompt, pipe.tokenizer, 77)
        acc_clip[step] = d_clip if acc_clip[step] is None else acc_clip[step] + d_clip

        # T5 direction: masked mean over real tokens
        if pipe.tokenizer_3 is not None:
            d_t5 = masked_mean(diff[77:], pos_prompt, pipe.tokenizer_3, 256)
            acc_t5[step] = d_t5 if acc_t5[step] is None else acc_t5[step] + d_t5

    # CLIP-L pooled direction (positions 0:768) — mirrors FLUX object steering
    if pos_pooled is not None and neg_pooled is not None:
        clipl_diff = (pos_pooled - neg_pooled)[:768]
        acc_clipl_pooled = clipl_diff if acc_clipl_pooled is None else acc_clipl_pooled + clipl_diff

    # CLIP-G pooled direction (positions 768:)
    if pos_pooled is not None and neg_pooled is not None:
        clipg_diff = (pos_pooled - neg_pooled)[768:]
        acc_clipg  = clipg_diff if acc_clipg is None else acc_clipg + clipg_diff

n = len(DIVERSE_PAIRS)

# Normalise — one unit direction per step
dir_clip_steps = {}
for step in range(NUM_STEPS):
    if acc_clip[step] is not None:
        avg = acc_clip[step] / n
        dir_clip_steps[step] = (avg / (avg.norm() + 1e-8)).to(DEVICE, dtype=DTYPE)

dir_t5_steps = {}
if pipe.tokenizer_3 is not None:
    for step in range(NUM_STEPS):
        if acc_t5[step] is not None:
            avg = acc_t5[step] / n
            dir_t5_steps[step] = (avg / (avg.norm() + 1e-8)).to(DEVICE, dtype=DTYPE)

dir_clipl_pooled = None
if acc_clipl_pooled is not None:
    avg = acc_clipl_pooled / n
    dir_clipl_pooled = (avg / (avg.norm() + 1e-8)).to(DEVICE, dtype=DTYPE)

dir_clipg = None
if acc_clipg is not None:
    avg   = acc_clipg / n
    dir_clipg = (avg / (avg.norm() + 1e-8)).to(DEVICE, dtype=DTYPE)

print(f"\nDone. Per-step directions: CLIP-L seq ({len(dir_clip_steps)} steps), "
      f"T5 ({len(dir_t5_steps)} steps), "
      f"CLIP-L pooled ({'yes' if dir_clipl_pooled is not None else 'no'}), "
      f"CLIP-G ({'yes' if dir_clipg is not None else 'no'})")

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageDraw
from itertools import product

def make_placeholder(label):
    img = Image.new('RGB', (512, 512), (40, 40, 40))
    ImageDraw.Draw(img).text((180, 240), f"{label}\nNaN/OOB", fill=(255, 80, 80))
    return img

def run(a_clip, a_t5, a_clipg, a_clp=0):
    counter = [0]
    def _ctx_hook(module, inp, out, _ac=a_clip, _at=a_t5):
        step = counter[0] % NUM_STEPS
        counter[0] += 1
        out_f = out.clone().float()
        d = dir_clip_steps[step].float()
        proj = torch.clamp(out_f[:, :77, :] @ d, min=0.0).unsqueeze(-1)
        out_f[:, :77, :] -= _ac * proj * d
        if step in dir_t5_steps:
            d = dir_t5_steps[step].float()
            proj = (out_f[:, 77:, :] @ d).unsqueeze(-1)  # no clip_negative — objects are diffuse in T5
            out_f[:, 77:, :] -= _at * proj * d
        return out_f.to(out.dtype)
    def _pooled_pre_hook(module, args, _ag=a_clipg, _aclp=a_clp):
        timestep, pooled = args
        pooled_f = pooled.clone().float()
        if dir_clipl_pooled is not None and _aclp != 0:
            d = dir_clipl_pooled.float()
            proj = torch.clamp(pooled_f[:, :768] @ d, min=0.0).unsqueeze(-1)
            pooled_f[:, :768] -= _aclp * proj * d
        if dir_clipg is not None and _ag != 0:
            d = dir_clipg.float()
            proj = (pooled_f[:, 768:] @ d).unsqueeze(-1)
            pooled_f[:, 768:] -= _ag * proj * d
        return (timestep, pooled_f.to(pooled.dtype))
    h1 = pipe.transformer.context_embedder.register_forward_hook(_ctx_hook)
    h2 = pipe.transformer.time_text_embed.register_forward_pre_hook(_pooled_pre_hook)
    try:
        with torch.no_grad():
            img = pipe(GEN_PROMPT, guidance_scale=GUIDANCE_SCALE,
                       num_inference_steps=NUM_STEPS,
                       generator=torch.Generator(DEVICE).manual_seed(SEED)).images[0]
        arr = np.array(img)
        if arr.mean() > 250 or arr.mean() < 5:
            img = make_placeholder(f"c={a_clip} t={a_t5} g={a_clipg}")
            print(f"c={a_clip} t={a_t5} g={a_clipg}: degenerate")
        else:
            print(f"c={a_clip} t={a_t5} g={a_clipg}: ok (mean={arr.mean():.1f})")
    except Exception as e:
        img = make_placeholder(f"c={a_clip} t={a_t5} g={a_clipg}")
        print(f"error: {e}")
    finally:
        h1.remove(); h2.remove()
    return img

# Sweep: rows = (C, T5, G) combos, cols = CLIP-L pooled values
row_keys = list(product(ALPHAS_C, ALPHAS_T, ALPHAS_G))
n_rows = len(row_keys)
n_cols = len(ALPHAS_CLP)

all_imgs = {}
for a_clip, a_t5, a_clipg in row_keys:
    for a_clp in ALPHAS_CLP:
        all_imgs[(a_clip, a_t5, a_clipg, a_clp)] = run(a_clip, a_t5, a_clipg, a_clp)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(4 * n_cols, 4 * n_rows), squeeze=False)
for r, (a_clip, a_t5, a_clipg) in enumerate(row_keys):
    for c, a_clp in enumerate(ALPHAS_CLP):
        ax = axes[r][c]
        ax.imshow(all_imgs[(a_clip, a_t5, a_clipg, a_clp)])
        ax.set_title(f"c={a_clip} t={a_t5} g={a_clipg} clp={a_clp}", fontsize=9)
        ax.axis("off")

plt.suptitle("Object steering — full alpha grid (CLIP-L × T5 × CLIP-G)", fontsize=11)
plt.tight_layout()
plt.show()

# To generate baseline image
clear_all_hooks()

with torch.no_grad():
    baseline = pipe(
        GEN_PROMPT,
        guidance_scale=GUIDANCE_SCALE,
        num_inference_steps=NUM_STEPS,
        generator=torch.Generator(DEVICE).manual_seed(SEED),
    ).images[0]

clear_all_hooks()
display(baseline)
# baseline.save("baseline.png")